apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  project: default
  source:
    # Replace this with your public GitHub repository URL.
    # The repository name must include a team member login/name as required by the subject.
    repoURL: https://github.com/thanthtetaung4/iot-taung.git
    targetRevision: master
    path: p3/confs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
