# P2: one VM, one K3s server, three web apps exposed by Ingress.

Vagrant.configure("2") do |config|
  config.vm.box = "luminositylabsllc/bento-ubuntu-26.04"

  config.vm.define "taungS" do |server|
    server.vm.hostname = "taungS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "taungS-p2"
      vb.cpus = 1
      vb.memory = 3052
    end

    server.vm.provision "shell", path: "scripts/install.sh"
    server.vm.provision "shell", path: "scripts/deploy.sh"
  end
end
